version: '3'
volumes:
  prometheus_data: {}
  grafana_data: {}
  scanner_data: {}
services:
  farm-proxy:
    image: braiinssystems/farm-proxy:22.07
    container_name: farm-proxy
    network_mode: "host"
    volumes:
      - "./config/sample.toml:/conf/farm_proxy.toml"
    environment:
      - CONF_PATH=/conf/farm_proxy.toml
      - RUST_LOG=debug
      - RUST_BACKTRACE=full
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "50"
        compress: "true"
  bos_scanner:
    image: braiinssystems/bos_monitor:v1.0.1
    container_name: bos_scanner
    volumes:
      - ./scan_crontab:/usr/local/share/scan_crontab
      - scanner_data:/mnt:rw
    network_mode: "host"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
      - scanner_data:/mnt
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    labels:
      org.label-schema.group: "monitoring"
  grafana:
    image: grafana/grafana:8.4.0
    container_name: grafana
    network_mode: "host"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/provisioning/grafana.ini
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/default_dashboards/farm-proxy/client_dashboard.json
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    labels:
      org.label-schema.group: "monitoring"
