version: '3'
volumes:
  prometheus_data: {}
  grafana_data: {}
  scanner_data: {}
services:
  farm-proxy:
    image: braiinssystems/farm-proxy:23.05 # Will be replaced with braiinssystems/farm-proxy:TAG upon public release
    container_name: farm-proxy
    network_mode: "host"
    volumes:
      - "./config/sample.toml:/conf/farm_proxy.toml"
    environment:
      - CONF_PATH=/conf/farm_proxy.toml
      - RUST_LOG=info
      - RUST_BACKTRACE=full
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "50"
        compress: "true"
    ulimits:
      nofile:
        hard: "1048576"
        soft: "262144"
  # metrics-exporter is a program, which performs device discovery on the defined network and pulls data from miners running a Stock FW. As a result, those data can be digested by Prometheus and visualized in Grafana dashboard, see dashboard "Farm Dashboard"
  metrics-exporter:
    image: braiinssystems/farm-monitor:23.01
    container_name: metrics-exporter
    network_mode: "host"
    volumes:
      - ./monitoring/metrics-exporter:/etc/metrics-exporter
      - scanner_data:/mnt:rw
    command:
      - '--config=/etc/metrics-exporter/metrics-exporter.toml'
      - '--sd-file=/mnt/bos_miners.json'
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
      - scanner_data:/mnt
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    labels:
      org.label-schema.group: "monitoring"
  grafana:
    image: grafana/grafana:9.5.1
    container_name: grafana
    network_mode: "host"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      #- GF_SECURITY_ADMIN_USER=admin
      #- GF_SECURITY_ADMIN_PASSWORD=admin
      #- GF_USERS_ALLOW_SIGN_UP=true
      - GF_PATHS_CONFIG=/etc/grafana/provisioning/grafana.ini
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/default_dashboards/farm-proxy/client_dashboard.json
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    labels:
      org.label-schema.group: "monitoring"
